# Check for all WikiPathways pathways in which taxon its genes/proteins are found (besides human)

SELECT DISTINCT ?wpid (group_concat(DISTINCT(?name);separator=" | ") as ?species) (count(DISTINCT(?taxon)) AS ?num) WHERE {  
  VALUES ?type { wd:Q7187 wd:Q8054}
  ?pathway wdt:P31 wd:Q4915012.
  ?pathway wdt:P2410 ?wpid.
  ?pathway wdt:P527 ?gene.
  ?gene wdt:P31 ?type.
  ?gene wdt:P703 ?taxon.
  ?taxon wdt:P225 ?name.
}
GROUP BY ?wpid
ORDER BY DESC(?num)
